# Generated by Django 4.0.4 on 2022-04-27 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0005_auto_20220427_1102"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sub_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Sub Category Title"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=55, verbose_name="Sub Category Slug"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Sub Category Description"
                    ),
                ),
                (
                    "sub_category_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sub category",
                        verbose_name="Sub Category Image",
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="Is Active?")),
                ("is_featured", models.BooleanField(verbose_name="Is Featured?")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Date"),
                ),
            ],
            options={
                "verbose_name_plural": "Sub_Categories",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Product_Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_envoi",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date envoi"),
                ),
                (
                    "lien_transporteur",
                    models.CharField(max_length=300, verbose_name="Suivi transport"),
                ),
                (
                    "type_envoi",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal"),
                            ("Eco", "Eco"),
                            ("Fast", "Fast"),
                            ("Very Fast", "Very Fast"),
                        ],
                        default="Normal",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.order",
                        verbose_name="Order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Credit_Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(verbose_name="numero de la carte"),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(verbose_name="Expiration date"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.sub_category",
                verbose_name="Product Sub Categoy",
            ),
        ),
    ]
