# Generated by Django 3.2.3 on 2022-05-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_sub_category_product_shipping_credit_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="category", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(verbose_name="Actif ?"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_featured",
            field=models.BooleanField(verbose_name="Vedette ?"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=55, verbose_name="raccourci"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="detail_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description detaillée"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(verbose_name="Actif ?"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(verbose_name="Vedette ?"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Prix"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Identifiant unique (SKU)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=160, verbose_name="Raccourci"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.sub_category",
                verbose_name="Sous-catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Nom"),
        ),
    ]
